#!/bin/bash
# This is a simple script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

set -e

echo Starting $( basename "$0" ) action hook...

if [ ! -d "${OPENSHIFT_DATA_DIR}.rbenv" ]; then
  ${OPENSHIFT_REPO_DIR}/1.install-ruby
fi

pushd "$OPENSHIFT_REPO_DIR" > /dev/null
echo "Create config files..."
cp config/redis.yml.openshift config/redis.yml
cp config/database.yml.openshift config/database.yml
cp config/environments/production.rb.openshift config/environments/production.rb
popd > /dev/null

echo Ended $( basename "$0" ) action hook.
