#!/bin/bash
# This is a simple script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

set -e

echo Starting $( basename "$0" ) action hook...

if [ -f "${OPENSHIFT_REPO_DIR}/1.install-rbenv" ]; then
	if [ ! -d "${OPENSHIFT_DATA_DIR}.rbenv" ]; then
	  echo Installing rbenv...
	  ${OPENSHIFT_REPO_DIR}/1.install-rbenv
	fi
fi

if [ -f "${OPENSHIFT_REPO_DIR}/1.install-rvm" ]; then
	if [ ! -d "${OPENSHIFT_DATA_DIR}.rvm" ]; then
	  echo Installing rvm...
	  ${OPENSHIFT_REPO_DIR}/1.install-rvm
	fi
fi

pushd "$OPENSHIFT_REPO_DIR" > /dev/null

if [ ! -f config/redis.yml ]; then
	echo "Creatin redis.yml file..."
	cp config/redis.yml.openshift config/redis.yml
fi

if [ ! -f config/database.yml ]; then
	echo "Creatin database.yml file..."
	cp config/database.yml.openshift config/database.yml
fi

if [ ! -f config/environments/production.rb ]; then
	echo "Creatin production.rb file..."
	cp config/environments/production.rb.openshift config/environments/production.rb
fi

popd > /dev/null

echo Ended $( basename "$0" ) action hook.
